before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then pear install pear/PHP_CodeSniffer; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then phpenv rehash; fi

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then phpcs -n -p --standard=PSR2 app/ public/index.php; fi

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
